"""add_cascade_to_bid_history_foreign_keys

Revision ID: 2504ca202299
Revises: 83c81b0e0b83
Create Date: 2026-04-02 12:07:13.824695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2504ca202299'
down_revision: Union[str, None] = '83c81b0e0b83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bid_history_ibfk_1', 'bid_history', type_='foreignkey')
    op.drop_constraint('bid_history_ibfk_2', 'bid_history', type_='foreignkey')
    op.create_foreign_key('bid_history_ibfk_1', 'bid_history', 'auctions', ['auction_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('bid_history_ibfk_2', 'bid_history', 'bids', ['bid_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bid_history_ibfk_1', 'bid_history', type_='foreignkey')
    op.drop_constraint('bid_history_ibfk_2', 'bid_history', type_='foreignkey')
    op.create_foreign_key('bid_history_ibfk_1', 'bid_history', 'auctions', ['auction_id'], ['id'])
    op.create_foreign_key('bid_history_ibfk_2', 'bid_history', 'bids', ['bid_id'], ['id'])
    # ### end Alembic commands ###
