"""add_cascade_to_all_remaining_auction_foreign_keys

Revision ID: 3a2d055a1e2a
Revises: 2504ca202299
Create Date: 2026-04-02 12:12:39.772699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a2d055a1e2a'
down_revision: Union[str, None] = '2504ca202299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Fix fraud_flags table
    op.drop_constraint('fraud_flags_ibfk_1', 'fraud_flags', type_='foreignkey')
    op.create_foreign_key('fraud_flags_ibfk_1', 'fraud_flags', 'auctions', ['auction_id'], ['id'], ondelete='CASCADE')
    
    # Fix payments table
    op.drop_constraint('payments_ibfk_1', 'payments', type_='foreignkey')
    op.create_foreign_key('payments_ibfk_1', 'payments', 'auctions', ['auction_id'], ['id'], ondelete='CASCADE')
    
    # Fix reports table
    op.drop_constraint('reports_ibfk_1', 'reports', type_='foreignkey')
    op.create_foreign_key('reports_ibfk_1', 'reports', 'auctions', ['auction_id'], ['id'], ondelete='CASCADE')
    
    # Fix auction_extensions table
    op.drop_constraint('auction_extensions_ibfk_1', 'auction_extensions', type_='foreignkey')
    op.create_foreign_key('auction_extensions_ibfk_1', 'auction_extensions', 'auctions', ['auction_id'], ['id'], ondelete='CASCADE')
    
    # Fix auction_winners table
    op.drop_constraint('auction_winners_ibfk_1', 'auction_winners', type_='foreignkey')
    op.create_foreign_key('auction_winners_ibfk_1', 'auction_winners', 'auctions', ['auction_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert fraud_flags table
    op.drop_constraint('fraud_flags_ibfk_1', 'fraud_flags', type_='foreignkey')
    op.create_foreign_key('fraud_flags_ibfk_1', 'fraud_flags', 'auctions', ['auction_id'], ['id'])
    
    # Revert payments table
    op.drop_constraint('payments_ibfk_1', 'payments', type_='foreignkey')
    op.create_foreign_key('payments_ibfk_1', 'payments', 'auctions', ['auction_id'], ['id'])
    
    # Revert reports table
    op.drop_constraint('reports_ibfk_1', 'reports', type_='foreignkey')
    op.create_foreign_key('reports_ibfk_1', 'reports', 'auctions', ['auction_id'], ['id'])
    
    # Revert auction_extensions table
    op.drop_constraint('auction_extensions_ibfk_1', 'auction_extensions', type_='foreignkey')
    op.create_foreign_key('auction_extensions_ibfk_1', 'auction_extensions', 'auctions', ['auction_id'], ['id'])
    
    # Revert auction_winners table
    op.drop_constraint('auction_winners_ibfk_1', 'auction_winners', type_='foreignkey')
    op.create_foreign_key('auction_winners_ibfk_1', 'auction_winners', 'auctions', ['auction_id'], ['id'])
    # ### end Alembic commands ###
